CREATE TABLE KHACHHANG (
	MaKH CHAR(5) PRIMARY KEY,
	HoTen VARCHAR(30),
	DiaChi VARCHAR(30),
	SoDT VARCHAR(15),
	LoaiKH VARCHAR(10)
);

CREATE TABLE BANG_DIA (
	MaBD CHAR(5) PRIMARY KEY,
	TenBD VARCHAR(25),
	TheLoai VARCHAR(25)
);

CREATE TABLE PHIEUTHUE (
	MaPT CHAR(5) PRIMARY KEY,
	MaKH CHAR(5),
	FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
	NgayThue SMALLDATETIME,
	NgayTra SMALLDATETIME,
	SoLuongThue INT
);

CREATE TABLE CHITIET_PM (
	MaPT CHAR(5),
	FOREIGN KEY (MaPT) REFERENCES PHIEUTHUE(MaPT),
	MaBD CHAR(5),
	FOREIGN KEY (MaBD) REFERENCES BANG_DIA(MaBD)
);

ALTER TABLE BANG_DIA
ADD CONSTRAINT CHK_theloai CHECK (TheLoai IN (N'ca nhạc', N'phim hành động', N'phim tình cảm', N'phim hoạt hình'));
GO

CREATE TRIGGER TRG_VIP
ON PHIEUTHUE
AFTER INSERT
AS
BEGIN
    DECLARE @LoaiKH VARCHAR(10), @SoLuongThue INT;

    SELECT @LoaiKH = LoaiKH FROM KHACHHANG WHERE MaKH = (SELECT MaKH FROM INSERTED);
    SELECT @SoLuongThue = SoLuongThue FROM INSERTED;

    IF (@LoaiKH != 'VIP' AND @SoLuongThue > 5)
    BEGIN
        PRINT(N'Khách hàng không phải loại VIP không được thuê với số lượng trên 5 băng đĩa.');
        ROLLBACK TRANSACTION;
    END
END;
GO

SELECT KH.MaKH, KH.HoTen
FROM KHACHHANG KH
INNER JOIN PHIEUTHUE PT ON KH.MaKH = PT.MaKH
INNER JOIN CHITIET_PM CP ON PT.MaPT = CP.MaPT
INNER JOIN BANG_DIA BD ON CP.MaBD = BD.MaBD
WHERE BD.TheLoai = N'phim tình cảm'
GROUP BY KH.MaKH, KH.HoTen
HAVING SUM(PT.SoLuongThue) > 3;

SELECT TOP 1 KH.MaKH, KH.HoTen
FROM KHACHHANG KH
INNER JOIN PHIEUTHUE PT ON KH.MaKH = PT.MaKH
WHERE KH.LoaiKH = 'VIP'
GROUP BY KH.MaKH, KH.HoTen
ORDER BY SUM(PT.SoLuongThue) DESC;

SELECT BD.TheLoai, KH.MaKH, KH.HoTen
FROM KHACHHANG KH
INNER JOIN PHIEUTHUE PT ON KH.MaKH = PT.MaKH
INNER JOIN CHITIET_PM CP ON PT.MaPT = CP.MaPT
INNER JOIN BANG_DIA BD ON CP.MaBD = BD.MaBD
GROUP BY BD.TheLoai, KH.MaKH, KH.HoTen
HAVING SUM(PT.SoLuongThue) = (
    SELECT MAX(TotalRentals)
    FROM (
        SELECT SUM(PT2.SoLuongThue) AS TotalRentals
        FROM PHIEUTHUE PT2
        INNER JOIN CHITIET_PM CP2 ON PT2.MaPT = CP2.MaPT
        INNER JOIN BANG_DIA BD2 ON CP2.MaBD = BD2.MaBD
        WHERE BD2.TheLoai = BD.TheLoai
        GROUP BY PT2.MaKH
    ) AS SubQuery
);
