CREATE TABLE DOCGIA (
	MaDG CHAR(5) PRIMARY KEY,
	HoTen VARCHAR(30),
	NgaySinh SMALLDATETIME,
	DiaChi VARCHAR(30),
	SoDT VARCHAR(15)
);

CREATE TABLE SACH (
	MaSach CHAR(5) PRIMARY KEY,
	TenSach VARCHAR(25),
	TheLoai VARCHAR(25),
	NhaXuatBan VARCHAR(30)
);

CREATE TABLE PHIEUTHUE (
	MaPT CHAR(5) PRIMARY KEY,
	MaDG CHAR(5),
	FOREIGN KEY (MaDG) REFERENCES DOCGIA(MaDG),
	NgayThue SMALLDATETIME,
	NgayTra SMALLDATETIME,
	SoSachThue INT
);

CREATE TABLE CHITIET_PT (
	MaPT CHAR(5),
	FOREIGN KEY (MaPT) REFERENCES PHIEUTHUE(MaPT),
	MaSach CHAR(5),
	FOREIGN KEY (MaSach) REFERENCES SACH(MaSach)
);
GO

CREATE TRIGGER TRG_KTNgayThue
ON PHIEUTHUE
FOR INSERT, UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM INSERTED
        WHERE DATEDIFF(DAY, NgayThue, NgayTra) > 10
    )
    BEGIN
        PRINT (N'Thời gian thuê sách không được vượt quá 10 ngày.');
        ROLLBACK TRANSACTION;
    END
END;
GO

CREATE TRIGGER TRG_KTSoSachThue
ON CHITIET_PT
AFTER INSERT, DELETE, UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM PHIEUTHUE PT
        WHERE PT.SoSachThue != (
            SELECT COUNT(*)
            FROM CHITIET_PT CT
            WHERE CT.MaPT = PT.MaPT
        )
    )
    BEGIN
        PRINT (N'Số sách thuê không khớp với chi tiết phiếu thuê.');
        ROLLBACK TRANSACTION;
    END
END;
GO

SELECT DISTINCT DG.MaDG, DG.HoTen
FROM DOCGIA DG
INNER JOIN PHIEUTHUE PT ON DG.MaDG = PT.MaDG
INNER JOIN CHITIET_PT CT ON PT.MaPT = CT.MaPT
INNER JOIN SACH S ON CT.MaSach = S.MaSach
WHERE S.TheLoai = 'Tin học' AND YEAR(PT.NgayThue) = 2007;

SELECT TOP 1 DG.MaDG, DG.HoTen
FROM DOCGIA DG
INNER JOIN PHIEUTHUE PT ON DG.MaDG = PT.MaDG
INNER JOIN CHITIET_PT CT ON PT.MaPT = CT.MaPT
INNER JOIN SACH S ON CT.MaSach = S.MaSach
GROUP BY DG.MaDG, DG.HoTen
HAVING COUNT(DISTINCT S.TheLoai) = (
    SELECT MAX(SoTheLoai)
    FROM (
        SELECT COUNT(DISTINCT S1.TheLoai) AS SoTheLoai
        FROM DOCGIA DG1
        INNER JOIN PHIEUTHUE PT1 ON DG1.MaDG = PT1.MaDG
        INNER JOIN CHITIET_PT CT1 ON PT1.MaPT = CT1.MaPT
        INNER JOIN SACH S1 ON CT1.MaSach = S1.MaSach
        GROUP BY DG1.MaDG
    ) AS Temp
);

SELECT S.TheLoai, S.TenSach
FROM SACH S
INNER JOIN CHITIET_PT CT ON S.MaSach = CT.MaSach
GROUP BY S.TheLoai, S.TenSach
HAVING COUNT(*) = (
    SELECT MAX(SoLanThue)
    FROM (
        SELECT S1.TheLoai, COUNT(*) AS SoLanThue
        FROM SACH S1
        INNER JOIN CHITIET_PT CT1 ON S1.MaSach = CT1.MaSach
        WHERE S1.TheLoai = S.TheLoai
        GROUP BY S1.TenSach, S1.TheLoai
    ) AS Temp
);
