CREATE TABLE NHANVIEN (
	MaNV CHAR(5) PRIMARY KEY,
	HoTen VARCHAR(20),
	NgayVL SMALLDATETIME,
	HSLuong NUMERIC(4, 2),
	MaPhong CHAR(5)
);

CREATE TABLE PHONGBAN (
	MaPhong CHAR(5) PRIMARY KEY,
	TenPhong VARCHAR(25),
	TruongPhong CHAR(5)
);

ALTER TABLE NHANVIEN
ADD FOREIGN KEY (MaPhong) REFERENCES PHONGBAN(MaPhong);

ALTER TABLE PHONGBAN
ADD FOREIGN KEY (TruongPhong) REFERENCES NHANVIEN(MaNV);

CREATE TABLE XE (
	MaXe CHAR(5) PRIMARY KEY,
	LoaiXe VARCHAR(20),
	SoChoNgoi INT,
	NamSX INT
);

CREATE TABLE PHANCONG (
	MaPC CHAR(5),
	MaNV CHAR(5),
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
	MaXe CHAR(5),
	FOREIGN KEY (MaXe) REFERENCES XE(MaXe),
	NgayDi SMALLDATETIME,
	NgayVe SMALLDATETIME,
	NoiDen VARCHAR(25)
);

ALTER TABLE XE
ADD CONSTRAINT CHK_NamSX CHECK (
    (LoaiXe = 'Toyota' AND NamSX >= 2006) OR LoaiXe <> 'Toyota'
);
GO

CREATE TRIGGER trg_Check_PhanCong
ON PHANCONG
AFTER INSERT, UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM inserted I
        JOIN NHANVIEN NV ON I.MaNV = NV.MaNV
        JOIN PHONGBAN PB ON NV.MaPhong = PB.MaPhong
        JOIN XE X ON I.MaXe = X.MaXe
        WHERE PB.TenPhong = 'Ngoại thành' AND X.LoaiXe <> 'Toyota'
    )
    BEGIN
        PRINT (N'Nhân viên thuộc phòng "Ngoại thành" chỉ được phân công lái xe loại Toyota.');
        ROLLBACK TRANSACTION;
    END
END;
GO

SELECT DISTINCT NV.MaNV, NV.HoTen
FROM NHANVIEN NV
INNER JOIN PHONGBAN PB ON NV.MaPhong = PB.MaPhong
INNER JOIN PHANCONG PC ON NV.MaNV = PC.MaNV
INNER JOIN XE X ON PC.MaXe = X.MaXe
WHERE PB.TenPhong = N'Nội thành'
  AND X.LoaiXe = 'Toyota'
  AND X.SoChoNgoi = 4;

SELECT NV.MaNV, NV.HoTen
FROM NHANVIEN NV
INNER JOIN PHONGBAN PB ON NV.MaNV = PB.TruongPhong
WHERE NOT EXISTS (
    SELECT 1
    FROM XE X
    WHERE NOT EXISTS (
        SELECT 1
        FROM PHANCONG PC
        WHERE PC.MaNV = NV.MaNV
          AND PC.MaXe = X.MaXe
    )
);

SELECT NV.MaNV, NV.HoTen
FROM NHANVIEN NV
JOIN PHANCONG PC ON NV.MaNV = PC.MaNV
JOIN XE X ON PC.MaXe = X.MaXe
WHERE X.LoaiXe = 'Toyota'
  AND NV.MaNV IN (
      SELECT TOP 1 NV1.MaNV
      FROM NHANVIEN NV1
      JOIN PHANCONG PC1 ON NV1.MaNV = PC1.MaNV
      JOIN XE X1 ON PC1.MaXe = X1.MaXe
      WHERE X1.LoaiXe = 'Toyota' AND NV1.MaPhong = NV.MaPhong
      GROUP BY NV1.MaNV
      ORDER BY COUNT(DISTINCT PC1.MaXe) ASC
  );
