CREATE TABLE KHACHHANG (
  MAKH CHAR(4) NOT NULL PRIMARY KEY,
	HOTEN VARCHAR(40) NOT NULL,
	DCHI VARCHAR(50) NOT NULL,
	SODT VARCHAR(20) NOT NULL,
	NGSINH SMALLDATETIME NOT NULL,
	DOANHSO MONEY NOT NULL,
	NGDK SMALLDATETIME NOT NULL
);

CREATE TABLE NHANVIEN (
  MANV CHAR(4) NOT NULL PRIMARY KEY,
	HOTEN VARCHAR(40) NOT NULL,
	NGVL SMALLDATETIME NOT NULL,
	SODT VARCHAR(20) NOT NULL
);

CREATE TABLE SANPHAM (
  MASP CHAR(4) NOT NULL PRIMARY KEY,
	TENSP VARCHAR(40) NOT NULL,
	DVT VARCHAR(20) NOT NULL,
	NUOCSX VARCHAR(40) NOT NULL,
	GIA MONEY NOT NULL
);

CREATE TABLE HOADON (
  SOHD INT NOT NULL PRIMARY KEY,
	NGHD SMALLDATETIME NOT NULL,
	MAKH CHAR(4) NOT NULL,
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
	MANV CHAR(4) NOT NULL,
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
	TRIGIA MONEY NOT NULL
);

CREATE TABLE CTHD (
  SOHD INT NOT NULL,
	FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
	MASP CHAR(4) NOT NULL,
	FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
	CONSTRAINT PK_CTHD PRIMARY KEY (SOHD, MASP),
	SL INT NOT NULL
);

ALTER TABLE SANPHAM
ADD GHICHU varchar(20);

ALTER TABLE KHACHHANG
ADD LOAIKH tinyint NOT NULL;

ALTER TABLE SANPHAM
ALTER COLUMN GHICHU varchar(100);

ALTER TABLE SANPHAM
DROP COLUMN GHICHU;

ALTER TABLE KHACHHANG
ALTER COLUMN LOAIKH varchar(40);

ALTER TABLE SANPHAM
ADD CONSTRAINT CK_DVT CHECK (DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'));

ALTER TABLE SANPHAM
ADD CONSTRAINT CK_GIA CHECK (GIA >= 500);

ALTER TABLE CTHD
ADD CONSTRAINT CK_SL CHECK (SL >= 1);

ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_NGAYDK CHECK (NGDK > NGSINH);
